services:
  - type: web
    name: farmaciaOnline-backend
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://farmaciaonline-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-xxxxx.render.com # será configurado depois
      - key: DB_DATABASE
        value: gerenciar_farmacia
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: senha_do_banco
